blank_issues_enabled: true

contact_links:
  - name: Ask a Question
    url: https://github.com/scarletoath/crude-twitch-viewer-bot/discussions/new?category=q-a
    about: |
      Receive help from the users and supporters.

  - name: Start a General Discussion
    url: https://github.com/scarletoath/crude-twitch-viewer-bot/discussions/new?category=general
    about: |
      Discuss and exchange with other users and supporters.
