name: format & lint

# Controls when the workflow will run
on: 
  push:
    tags:
      - 'v*'
  workflow_dispatch: {}
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Run the black formatter
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: psf/black@stable
      with: 
        options: "--skip-string-normalization --line-length 119 --check"

  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'
      - name: Get packages via poetry
        run: poetry install
      - name: Run pylint
        run: |
          find . -type f -name "*.py" | xargs poetry run pylint --fail-under 7
          
        
